<!DOCTYPE html>
<html lang=""  itemscope itemtype="http://schema.org/Blog">
<head>
        <!–– Made with Lockdown: https://github.com/fferegrino/lockdown ––>
<meta charset="utf-8" />
<link rel="stylesheet" href="/css/main.css" />

        
</head>

<body>  
        <header class="site-header ui">
    <div class="wrapper menu">
      <nav class="site-nav">
        <a href="#" class="menu-icon">
          <svg viewBox="0 0 18 15">
            <path fill="#424242" d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.031C17.335,0,18,0.665,18,1.484L18,1.484z"/>
            <path fill="#424242" d="M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0c0-0.82,0.665-1.484,1.484-1.484 h15.031C17.335,6.031,18,6.696,18,7.516L18,7.516z"/>
            <path fill="#424242" d="M18,13.516C18,14.335,17.335,15,16.516,15H1.484C0.665,15,0,14.335,0,13.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.031C17.335,12.031,18,12.696,18,13.516L18,13.516z"/>
          </svg>
        </a>
        <div class="trigger">
          <a class="link page-link" href="/">Home</a>
          <a class="link page-link" href="/about">About</a>
          <a class="link page-link" href="/search">Search</a>
        </div>
      </nav>
    </div>
    <div class="wrapper title">
      <div class="pure-g">
        <div class="pure-u-1-24 title-number"><span>1</span></div>
        <div class="pure-u-11-24 content-window">
          <a class="site-title" href="/">That C# guy</a>
        </div>
        <div class="pure-u-12-24 header-menu">
          <ul>
            <li class="datascience"><a href="/tag/data-science/">Data Science!</a></li>
            <li class="youtube"><a href="https://www.youtube.com/c/thatcsharpguy">YouTube<a></li>
            <li class="csharp"><a href="/tag/aprendecsharp/">Aprende C#</a></li>
            <li class="xamarin"><a href="/tag/xamarin/">Xamarin</a></li>
          </ul>
        </div>
      </div>
  
  </header>
        <div class="page-content">
            <div class="wrapper">
                
<h1></h1>

<p>El framework de .NET cuenta con el mecanismo de excepciones para reportar errores que ocurren en tiempo de ejecución dentro de los programas que lo usan. Todo este mecanismo se centra alrededor de los tipos de dato <code>Exception</code>.</p>
<p>El tipo de dato <code>Exception</code> hereda directamente de <code>System.Object</code>, y es uno de los tipos fundamentales del framework (sin contar los nativos). Las <code>Exception</code> tienen la particularidad de poder ser usadas junto con la instrucción <code>throw</code>, que en inglés significa &quot;lanzar&quot;, así que es muy probable que hayas previamente escuchado la expresión <em>&quot;lanzar una excepción&quot;</em>.</p>
<p>Una API puede elegir lanzar una excepción cada vez que la ejecución de un programa llega a un estado en el cual es imposible seguir ejecutándose. Algunos ejemplos en los que sucede esto son:</p>
<ul>
<li>Cuando se intenta convertir una cadena en un número, pero esta no tiene el formato adecuado se lanza una excepción del tipo <code>FormatException</code></li>
<li>Cuando dentro de un arreglo intentamos acceder a una posición fuera del rango de este obtendremos una del tipo: <code>IndexOutOfRangeException</code></li>
<li>Cuando intentamos abrir un archivo no existente será <code>FileNotFoundException</code> la que aparezca</li>
<li>Cuando intentamos dividir un número entre 0 se nos aparecerá una <code>DivideByZeroException</code></li>
</ul>
<p>En este diagrama aparecen las algunas excepciones que existen en el framework por defecto, relacionadas por su jerarquía. Es importante señalar la jerarquía ya que tiene una utilidad muy peculiar con las excepciones que veremos más adelante:</p>
<p>&lt;img src=&quot;/images/aprende-c-sharp__ex__diagram.png&quot; title=<>Exceptions</> /&gt;</p>
<h2 id="usando-throw-para-lanzar-excepciones">Usando <code>throw</code> para lanzar excepciones</h2>
<p>La forma de lanzar una excepción es usando la palabra <code>throw</code> seguido de la instancia de excepción que vamos a lanzar:</p>
<pre><code class="language-csharp">throw new Exception(&quot;Hey, soy el mensaje de la excepción&quot;);

var ex = new FormatException(&quot;Hey, soy una excepción guardada en una variable&quot;);
throw ex;
</code></pre>
<h2 id="excepciones-personalizadas">Excepciones personalizadas</h2>
<p>Mientras que las excepciones por defecto en C# son genéricas y sirven bien al framework, es probable que para nuestra aplicación no sean lo más expresivas posibles y tratar de adecuarlas puede complicarnos la escritura de código. Es por eso que, en caso de ser necesario, podemos crear nuestras propias excepciones, basta con que estas deriven de <code>Exception</code>. Por ejemplo:</p>
<pre><code class="language-csharp">public class TienesMuchosGatosException : Exception
// ...
</code></pre>
<p>Ahora, ya podríamos hacer uso de esta excepción:</p>
<pre><code class="language-csharp">// ...
        if (value &gt; 1)
            throw new TienesMuchosGatosException();
        _numeroGatos = value;
// ...
</code></pre>
<p>Pero no solo eso, sino que podemos añadirle constructores y propiedades nuevas a la excepción para que esta le dé más información a quién está usando nuestro código:</p>
<pre><code class="language-csharp">public class TienesMuchosGatosException : Exception
{
    public int NumeroGatos { get; private set; }

    public TienesMuchosGatosException(int numeroGatos) 
        : base(&quot;¡&quot; + numeroGatos + &quot; son muchos gatos!&quot;)
    {
        NumeroGatos = numeroGatos;
    }
}

// En alguna otra parte del código:
// ...
        if (value &gt; 1)
            throw new TienesMuchosGatosException(value);
        _numeroGatos = value;
// ...
</code></pre>
<p>Como te puedes dar cuenta, estamos llamando al constructor de la clase base pasándole un mensaje (hay otro constructor que también recibe una instancia de <code>Exception</code> que podemos emplear para adjuntar cualquier otra excepción que hayamos atrapado para mayor información).</p>
<p>Entonces, ahora ya con estas modificaciones, si llamamos al siguiente código:</p>
<pre><code class="language-csharp">var adulto = new Adulto();
adulto.NumeroGatos = 10;
</code></pre>
<p>Nuestro programa fallará, pero le dejará al desarrollador más información:</p>
<pre>
Unhandled Exception:
Excepciones.TienesMuchosGatosException: ¡10 son muchos gatos!
  at Excepciones.Adulto.set_NumeroGatos (System.Int32 value) [0x00009] in /Users/fferegrino/Documents/github/aprende-c-sharp/excepciones/Adulto.cs:17 
  at Excepciones.Program.Main (System.String[] args) [0x00007] in /Users/fferegrino/Documents/github/aprende-c-sharp/excepciones/Program.cs:22 
[ERROR] FATAL UNHANDLED EXCEPTION: Excepciones.TienesMuchosGatosException: ¡10 son muchos gatos!
  at Excepciones.Adulto.set_NumeroGatos (System.Int32 value) [0x00009] in /Users/fferegrino/Documents/github/aprende-c-sharp/excepciones/Adulto.cs:17 
  at Excepciones.Program.Main (System.String[] args) [0x00007] in /Users/fferegrino/Documents/github/aprende-c-sharp/excepciones/Program.cs:22 
</pre>
<h2 id="manejo-de-excepciones">Manejo de excepciones</h2>
<p>La misión de las expresiones es bastante clara: indicar que el problema no puede continuar operando en su estado actual, y como tal, terminarlo. Sin embargo, nosotros los programadores podemos <em>manejar</em> la excepción y darle un tratamiento adecuado al programa para que este siga operando. Esto se logra con el bloque <code>try-catch</code>. Este bloque cuenta con dos partes:</p>
<ul>
<li>El <em>intentar</em>, en donde ponemos el código que podría generar una excepción</li>
<li>El <em>atrapar</em>, en donde reaccionaremos eventualmente a la excepción ocurrida</li>
</ul>
<p>Su sintaxis es así:</p>
<pre><code class="language-csharp">var adulto2 = new Adulto();
try
{
    // Intentamos algo peligroso:
    adulto2.NumeroGatos = Int32.MaxValue;
}
catch (TienesMuchosGatosException te)
{
    // Manejamos la excepción relacionada con los gatos:
    Console.WriteLine(&quot;Ooops, no puedes tener &quot; + te.NumeroGatos + &quot; gatos&quot;);
}
</code></pre>
<h3 id="manejo-selectivo-de-excepciones">Manejo selectivo de excepciones</h3>
<p>En el código anterior únicamente estamos manejando excepciones del tipo <code>TienesMuchosGatosException</code>, pero ¿qué pasaría si al establecer la propiedad también pudiéramos obtener excepciones de otro tipo? pues para eso podemos combinar los bloques <code>catch</code>:</p>
<pre><code class="language-csharp">try
{
    // Intentamos algo peligroso:
    adulto2.NumeroGatos = Int32.MaxValue;
}
catch (TienesMuchosGatosException te)
{
    // Manejamos la excepción relacionada con los gatos:
    Console.WriteLine(&quot;Ooops, no puedes tener &quot; + te.NumeroGatos + &quot; gatos&quot;);
}
catch(NullReferenceException ne)
{
    // Manejamos el error relacionado con objetos nulos
} 
catch(ArithmeticException)
{
    // Manejamos cualquier error relacionad 
    // con desborde de números o divisiones entre 0
}
catch
{
    // Manejamos cualquier otra excepcion
}
</code></pre>
<p>A estos bloques de captura de excepciones se decide si se accede o no de manera secuencial, es decir, en caso de que ocurra una excepción primero verifica si la excepción es del tipo <code>TienesMuchos...</code>, si no, verifica si es del tipo <code>NullReference...</code>, si no, verifica si es del tipo <code>Arithmetic...</code> y si no es cualquiera, entra el último bloque que atrapará cualquier excepción.</p>
<h3 id="variantes-de-catch">Variantes de <code>catch</code></h3>
<p>En el ejemplo de código anterior hay dos variantes de <code>catch</code>. La primera, que no especifica un identificador para la exepción (<code>catch(ArithmeticException)</code>) que usamos para cuando sólo nos interesa más que saber qué tipo de excepción ocurrió y no conocer más detalles de esta. Y la segunda <code>catch</code> que es una forma corta de escribir <code>catch(Exception)</code>, y esta se usa para cuando lo que nos interesa es saber que ocurrió una excepción pero no nos interesa ni de qué tipo fue.</p>
<h3 id="la-jerarquia-en-el-catch">La jerarquía en el <code>catch</code></h3>
<p>Es en el <code>catch</code> en donde es importante la jerarquía de las excepciones. Por ejemplo, en el código anterior, el bloque <code>catch(ArithmeticException)</code> atrapará tanto las de tipo <code>NotFiniteNumberException</code>, <code>OverflowException</code>, y <code>DivideByZeroException</code>. Porque estas heredan de <code>ArithmeticException</code>.</p>
<p>En otras ocasiones verás (o utilizarás) la vieja confiable <code>catch(Exception e)</code>, que básicamente atrapará todo lo que pase por ella, puesto que <code>Exception</code> es la clase base. Hay contados casos en los que diría que es recomendable emplear este <code>catch</code> ya que, al capturar <strong>cualquier</strong> tipo de excepción, puede ser que tu programa esté fallando en alguna parte que tu no tenías contemplada y no darte cuenta porque &quot;nunca&quot; ocurrió una excepción.</p>
<h3 id="relanzando-excepciones">Relanzando excepciones</h3>
<p>Hay ocasiones en las que tal vez quieras manejar una excepcion capturada con el único fin de realizar alguna tarea de registro, pero dejar que siga fallando como si no la hubieras atrapado. Para esos casos, puedes usar la instrucción <code>throw</code> solamente:</p>
<pre><code class="language-csharp">try
{
    throw new NotImplementedException();
}
catch(Exception e)
{
    // Logging
    throw;
}
</code></pre>
<p>Tal vez te sientas tentado a colocar el identificador para relanzar la excepción (<code>throw e;</code>), pero esto lo que hará es destruir información potencialmente valiosa que ya contiene la excepción, así que no deberías hacerlo.</p>


            </div>
          </div>
        
</body>
</html>
